services:
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /Users/gabrielparizet/workspace/rumbl/data:/var/lib/postgresql/data

